export const GET_CUSTOMER_SAVINGS_DATA_START = "GET_CUSTOMER_SAVINGS_DATA_START";
export const GET_CUSTOMER_SAVINGS_DATA_SUCCESS = "GET_CUSTOMER_SAVINGS_DATA_SUCCESS";
export const GET_CUSTOMER_SAVINGS_DATA_FAIL = "GET_CUSTOMER_SAVINGS_DATA_FAIL";
export const GET_CUSTOMER_SAVINGS_DATA = "GET_CUSTOMER_SAVINGS_DATA";

export default {
  GET_CUSTOMER_SAVINGS_DATA_START,
  GET_CUSTOMER_SAVINGS_DATA_SUCCESS,
  GET_CUSTOMER_SAVINGS_DATA_FAIL,
  GET_CUSTOMER_SAVINGS_DATA,
};
