export const SAVE_PERSONAL_DETAILS = "SAVE_PERSONAL_DETAILS";
export const SAVE_EMAIL_VERIFICATION_ID = "SAVE_EMAIL_VERIFICATION_ID";

export default { SAVE_PERSONAL_DETAILS, SAVE_EMAIL_VERIFICATION_ID };
