export const GET_RECENT_SAVING_TRANSACTIONS_DATA_START = "GET_RECENT_SAVING_TRANSACTIONS_DATA_START";
export const GET_RECENT_SAVING_TRANSACTIONS_DATA_SUCCESS = "GET_RECENT_SAVING_TRANSACTIONS_DATA_SUCCESS";
export const GET_RECENT_SAVING_TRANSACTIONS_DATA_FAIL = "GET_RECENT_SAVING_TRANSACTIONS_DATA_FAIL";
export const GET_RECENT_SAVING_TRANSACTIONS_DATA = "GET_RECENT_SAVING_TRANSACTIONS_DATA";

export default {
  GET_RECENT_SAVING_TRANSACTIONS_DATA_START,
  GET_RECENT_SAVING_TRANSACTIONS_DATA_SUCCESS,
  GET_RECENT_SAVING_TRANSACTIONS_DATA_FAIL,
  GET_RECENT_SAVING_TRANSACTIONS_DATA,
};
