export const GET_APPLICATION_BOOTSTRAP_DATA_SUCCESS = "GET_APPLICATION_BOOTSTRAP_DATA_SUCCESS";
export const GET_APPLICATION_BOOTSTRAP_DATA_FAIL = "GET_APPLICATION_BOOTSTRAP_DATA_FAIL";
export const GET_APPLICATION_BOOTSTRAP_DATA = "GET_APPLICATION_BOOTSTRAP_DATA";

export default {
  GET_APPLICATION_BOOTSTRAP_DATA_SUCCESS,
  GET_APPLICATION_BOOTSTRAP_DATA_FAIL,
  GET_APPLICATION_BOOTSTRAP_DATA,
};
