export const GET_SAVINGS_CONFIGURATION_DATA_START = "GET_SAVINGS_CONFIGURATION_DATA_START";
export const GET_SAVINGS_CONFIGURATION_DATA_SUCCESS = "GET_SAVINGS_CONFIGURATION_DATA_SUCCESS";
export const GET_SAVINGS_CONFIGURATION_DATA_FAIL = "GET_SAVINGS_CONFIGURATION_DATA_FAIL";
export const GET_SAVINGS_CONFIGURATION_DATA = "GET_SAVINGS_CONFIGURATION_DATA";

export default {
  GET_SAVINGS_CONFIGURATION_DATA_START,
  GET_SAVINGS_CONFIGURATION_DATA_SUCCESS,
  GET_SAVINGS_CONFIGURATION_DATA_FAIL,
  GET_SAVINGS_CONFIGURATION_DATA,
};
